const peliculas = [
    { id: 1, titulo: "Inception", anio: 2010, genero: "Ciencia Ficción", duracion: "148 min", director: "Christopher Nolan", actores: ["Leonardo DiCaprio","Joseph Gordon-Levitt","Elliot Page"], sinopsis: "Un ladrón que roba secretos corporativos a través de los sueños.", reseña: "Obra maestra del cine moderno.", calificacion: 4.8, imagen: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg" },
    { id: 2, titulo: "The Dark Knight", anio: 2008, genero: "Acción", duracion: "152 min", director: "Christopher Nolan", actores: ["Christian Bale","Heath Ledger","Aaron Eckhart"], sinopsis: "Batman enfrenta al Joker.", reseña: "Heath Ledger icónico.", calificacion: 4.9, imagen: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg" },
    { id: 3, titulo: "Interstellar", anio: 2014, genero: "Ciencia Ficción", duracion: "169 min", director: "Christopher Nolan", actores: ["Matthew McConaughey","Anne Hathaway","Jessica Chastain"], sinopsis: "Viaje a través de un agujero de gusano.", reseña: "Visualmente impresionante.", calificacion: 4.7, imagen: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg" },
    { id: 4, titulo: "Gladiator", anio: 2000, genero: "Acción", duracion: "155 min", director: "Ridley Scott", actores: ["Russell Crowe","Joaquin Phoenix","Connie Nielsen"], sinopsis: "General romano busca venganza.", reseña: "Épico de culto.", calificacion: 4.7, imagen: "https://image.tmdb.org/t/p/original/p08mUnCktZ2opGihZTAn7OqzOoi.jpg" },
    { id: 5, titulo: "Avatar", anio: 2009, genero: "Aventura", duracion: "162 min", director: "James Cameron", actores: ["Sam Worthington","Zoe Saldana","Sigourney Weaver"], sinopsis: "Marine en Pandora.", reseña: "Revolucionaria en efectos.", calificacion: 4.5, imagen: "https://image.tmdb.org/t/p/w500/kyeqWdyUXW608qlYkRqosgbbJyK.jpg" },
    { id: 6, titulo: "Parasite", anio: 2019, genero: "Drama", duracion: "132 min", director: "Bong Joon-ho", actores: ["Song Kang-ho","Lee Sun-kyun","Cho Yeo-jeong"], sinopsis: "Familia pobre se infiltra en familia rica.", reseña: "Sátira social perfecta.", calificacion: 4.8, imagen: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg" },
    { id: 7, titulo: "Spider-Man: Into the Spider-Verse", anio: 2018, genero: "Animación", duracion: "117 min", director: "Bob Persichetti", actores: ["Shameik Moore","Jake Johnson","Hailee Steinfeld"], sinopsis: "Miles Morales Spider-Man.", reseña: "Revolución en animación.", calificacion: 4.9, imagen: "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg" },
    { id: 8, titulo: "The Matrix", anio: 1999, genero: "Ciencia Ficción", duracion: "136 min", director: "Lana Wachowski", actores: ["Keanu Reeves","Laurence Fishburne","Carrie-Anne Moss"], sinopsis: "Realidad es una simulación.", reseña: "Hito cultural.", calificacion: 4.7, imagen: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg" },
    { id: 9, titulo: "Get Out", anio: 2017, genero: "Terror", duracion: "104 min", director: "Jordan Peele", actores: ["Daniel Kaluuya","Allison Williams","Bradley Whitford"], sinopsis: "Joven visita familia de novia.", reseña: "Thriller psicológico.", calificacion: 4.6, imagen: "https://image.tmdb.org/t/p/original/mE24wUCfjK8AoBBjaMjho7Rczr7.jpg" },
    { id: 10, titulo: "Whiplash", anio: 2014, genero: "Drama", duracion: "107 min", director: "Damien Chazelle", actores: ["Miles Teller","J.K. Simmons","Paul Reiser"], sinopsis: "Joven baterista busca grandeza.", reseña: "Intensa y adictiva.", calificacion: 4.7, imagen: "https://tse4.mm.bing.net/th/id/OIP.Ptgpx4WqC3wI1Z0H5EGhAwAAAA?w=414&h=600&rs=1&pid=ImgDetMain&o=7&rm=3" }
];